import Head from "next/head";
import Table from "../components/table";
import Form from "../components/form";
import { BiUserPlus } from "react-icons/bi";
import { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { toggleChangeAction } from "../redux/reducer";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const dispatch = useDispatch();
  const handler = () => {
    dispatch(toggleChangeAction());
  };
  return (
    <section>
      <Head>
        <title>NextJS CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="py-10 text-xl font-bold text-center md:text-5xl">
          Employees Management
        </h1>
        <div className="container flex justify-between py-5 mx-auto border-b">
          <div className="flex gap-3 left">
            <button
              onClick={handler}
              className="flex items-center px-4 py-2 text-white border rounded-md bg-slate-400 hover:cursor-pointer hover:bg-gray-600"
            >
              Add Employee
              <span className="px-1">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>
        </div>
        {/*collabable form */}

        {visible ? <Form></Form> : <></>}

        {/*table */}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
